version: "3"
services:
  runTest:
    image: phuocleautoqa/selenium
    environment:
      - BROWSER
      - HUB_HOST=hub
      - THREAD_COUNT
      - TEST_SUITE
    volumes:
      - /home/selenium-docker/test-suites
      - /home/selenium-docker/test-output
      # - ./output/vendor-portal:/home/selenium-docker/test-output/vendor-portal
      # - ./output/flight-reservation:/home/selenium-docker/test-output/flight-reservation
