version: "3"
services:
  runTest:
    image: phuocleautoqa/selenium
    environment:
      - BROWSER
      - HUB_HOST=hub
      - THREAD_COUNT
      - TEST_SUITE
    volumes:
#      - ./output:/home/selenium-docker/test-output
      - ./extent-report:/home/selenium-docker/extent-report
